In [1]:
import torch
import numpy as np
torch.set_printoptions(precision=6)

### 创建张量(list)

In [2]:
torch.Tensor([1,2,3])

tensor([1., 2., 3.])

### torch.ones()/zeros()/empty()

In [3]:
torch.ones([2,3])
torch.zeros([2,3])
torch.empty([2,3])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### np.array转换

In [4]:
arr = np.arange(12).reshape(3,4)
torch.Tensor(arr)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

###  整型数组

In [5]:
torch.randint(low=0, high=3, size=[3,4])

tensor([[1, 1, 1, 0],
        [2, 0, 1, 0],
        [2, 2, 2, 1]])

### 张量的方法和属性

In [6]:
t1 = torch.Tensor([[[1]]])

In [7]:
t1.item()

1.0

In [8]:
t2 = torch.Tensor([[[1, 2]]])

In [9]:
# t2.item() 只能有一个值

### 转换成numpy类型

In [10]:
t2.numpy()

array([[[1., 2.]]], dtype=float32)

### 获取形状

In [11]:
t2.size()

torch.Size([1, 1, 2])

### 形状的修改 浅拷贝

In [12]:
t2.view([-1])

tensor([1., 2.])

In [13]:
t2.view([1,2])

tensor([[1., 2.]])

### 获取阶数

In [14]:
t2.dim()

3

### 获取最大值

In [15]:
t2.max()

tensor(2.)

### 转置

In [16]:
t3 = torch.Tensor(np.arange(24).reshape(2,3,4))

In [17]:
t3

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [18]:
t3.transpose(0,1)

tensor([[[ 0.,  1.,  2.,  3.],
         [12., 13., 14., 15.]],

        [[ 4.,  5.,  6.,  7.],
         [16., 17., 18., 19.]],

        [[ 8.,  9., 10., 11.],
         [20., 21., 22., 23.]]])

In [19]:
t3.permute(1,2,0)

tensor([[[ 0., 12.],
         [ 1., 13.],
         [ 2., 14.],
         [ 3., 15.]],

        [[ 4., 16.],
         [ 5., 17.],
         [ 6., 18.],
         [ 7., 19.]],

        [[ 8., 20.],
         [ 9., 21.],
         [10., 22.],
         [11., 23.]]])

### 取值和切片

In [20]:
t4 = t3.permute(1,2,0)

In [21]:
t4

tensor([[[ 0., 12.],
         [ 1., 13.],
         [ 2., 14.],
         [ 3., 15.]],

        [[ 4., 16.],
         [ 5., 17.],
         [ 6., 18.],
         [ 7., 19.]],

        [[ 8., 20.],
         [ 9., 21.],
         [10., 22.],
         [11., 23.]]])

In [22]:
t4[1, 2, 1] = 18

In [23]:
t4[0, :, :]

tensor([[ 0., 12.],
        [ 1., 13.],
        [ 2., 14.],
        [ 3., 15.]])

### torch的数据类型

In [24]:
t4.dtype

torch.float32

In [25]:
torch.ones([1,2], dtype=torch.float32).dtype

torch.float32

In [26]:
t5 = torch.Tensor(np.arange(12, dtype=np.int32))

In [27]:
t5.dtype

torch.float32

In [28]:
t5.int()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=torch.int32)

In [29]:
torch.tensor(np.array(12), dtype=torch.float32).dtype

torch.float32

In [30]:
torch.LongTensor(1,2).dtype

torch.int64

### torch.Tnsor和torch.tensor

In [31]:
torch.Tensor([1,1])

tensor([1., 1.])

In [32]:
torch.FloatTensor(1)

tensor([8.449226e-39])

### tensor相加

In [39]:
x, y = torch.ones(2,5), torch.rand(2,5)
y

tensor([[0.928270, 0.821194, 0.785410, 0.350239, 0.913368],
        [0.384682, 0.044499, 0.448167, 0.295384, 0.039900]])

In [40]:
x+y

tensor([[1.928270, 1.821194, 1.785410, 1.350239, 1.913368],
        [1.384681, 1.044499, 1.448167, 1.295384, 1.039900]])

In [ ]:
### 新建空间相加

In [41]:
torch.add(x,y)

tensor([[1.928270, 1.821194, 1.785410, 1.350239, 1.913368],
        [1.384681, 1.044499, 1.448167, 1.295384, 1.039900]])

In [42]:
x.add(y)

tensor([[1.928270, 1.821194, 1.785410, 1.350239, 1.913368],
        [1.384681, 1.044499, 1.448167, 1.295384, 1.039900]])

### 就地修改

In [44]:
x.add_(y)

tensor([[1.928270, 1.821194, 1.785410, 1.350239, 1.913368],
        [1.384681, 1.044499, 1.448167, 1.295384, 1.039900]])

### CUDA中的tensor

In [53]:
torch.cuda.is_available()

False

In [54]:
pip list

Package              Version
-------------------- -----------
anyio                3.6.1
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
asttokens            2.0.7
attrs                22.1.0
Babel                2.10.3
backcall             0.2.0
beautifulsoup4       4.11.1
bleach               5.0.1
certifi              2022.6.15
cffi                 1.15.1
charset-normalizer   2.1.0
colorama             0.4.5
debugpy              1.6.2
decorator            5.1.1
defusedxml           0.7.1
entrypoints          0.4
executing            0.9.1
fastjsonschema       2.16.1
future               0.18.2
idna                 3.3
importlib-metadata   4.12.0
ipykernel            6.15.1
ipython              8.4.0
ipython-genutils     0.2.0
jedi                 0.18.1
Jinja2               3.1.2
json5                0.9.9
jsonschema           4.9.1
jupyter-client       7.3.4
jupyter-core         4.11.1
jupyter-server       1.18.1
jupyterlab           3.4.4
jupyterlab-pygments  0.2.2
jupyter

In [55]:
device = torch.device("cuda")

In [56]:
device

device(type='cuda')

In [57]:
torch.zeros([2,3], device=device)

AssertionError: Torch not compiled with CUDA enabled